### ISSUE TITLE
Bug? Hide alt text when mousing over button

### ISSUE THREAD

**Issue by Norc** [Kekilla0/TokenBar#13]
Foundry 0.62, D&D5E 0.92, TokenBar 0.1.02, Electron as GM. Only module installed.

When I mouse over the bar, such as for a SRD skeleton, i get what looks like an ID value: x0kAA4sklj;ajkl;g whatever. Not very helpful. It does not appear when Alt is depressed, strangely.

**Comment by Kekilla0** [comment]
No idea why the ID is showing when hovered. Plan on removing. Thanks for the feedback.

**Comment by Kekilla0** [comment]
updated and fixed with v0.1.2
