### ISSUE TITLE
Change Roll Advantage to SHIFT instead of ALT

### ISSUE THREAD

**Issue by TheTercept** [Kekilla0/TokenBar#2]
Uses the same existing shortcuts as Better Rolls, would be easier to remember one (common) way to roll for advantage and disadvantage.

**Comment by Norc** [comment]
Could you please make this an option, not global? Alt is what MQoL uses and is great. Also Shift will interfere with MQoL Speed Roll abilities.

**Comment by Kekilla0** [comment]
> Could you please make this an option, not global? Alt is what MQoL uses and is great. Also Shift will interfere with MQoL Speed Roll abilities.

This will only apply when using betterrolls5e

**Comment by Kekilla0** [comment]
This has been resolved as of v0.1.2
