### ISSUE TITLE
Deduplicating efforts with Token Action Hud

### ISSUE THREAD

**Issue by bryancasler** [Kekilla0/TokenBar#21]
Hi @Kekilla0, just last night I submitted a pull request with some UI touch-ups (https://github.com/Kekilla0/TokenBar/pull/20). Today I learned about Token Action Hud and it seems to be a nearly identical module with the same ambitions. Wanted to get it on your radar and see if you might be interested in combing efforts.

https://github.com/espositos/fvtt-tokenactionhud

**Comment by Kekilla0** [comment]
Token Bar is more or less discontinued and out of development. Token Action Hud is the logical successor.

**Comment by bryancasler** [comment]
Would you mind updating the Module and Repo to reflect that? Cursor Zoom recently did something similar.

https://foundryvtt.com/packages/cursor-zoom/
https://github.com/itamarcu/CursorZoom
